"""rename event_type to category

Revision ID: 8158c8e99233
Revises: 7f81350c3c0b
Create Date: 2026-05-11 22:11:40.082066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8158c8e99233'
down_revision: Union[str, Sequence[str], None] = '7f81350c3c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('category', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.drop_column('events', 'event_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.drop_column('events', 'category')
    # ### end Alembic commands ###
